import image1link from '../../assets/imageSliderPhotos/IMG_2501.jpg';
import image2link from '../../assets/imageSliderPhotos/IMG_2561.jpg';
import image3link from '../../assets/imageSliderPhotos/IMG_3585.jpg';
import image4link from '../../assets/imageSliderPhotos/IMG_1001.jpg';
import image5link from '../../assets/imageSliderPhotos/IMG_3102.jpg';
import image6link from '../../assets/imageSliderPhotos/IMG_3349.jpg';
import image7link from '../../assets/imageSliderPhotos/IMG_4477.JPG';
import image8link from '../../assets/imageSliderPhotos/IMG_4534.jpg';
import image9link from '../../assets/imageSliderPhotos/IMG_4872.jpg';
import image10link from '../../assets/imageSliderPhotos/IMG_4081.jpg';
import image11link from '../../assets/imageSliderPhotos/IMG_0881.jpg';
import image12link from '../../assets/imageSliderPhotos/IMG_1343.jpg';
import image13link from '../../assets/imageSliderPhotos/IMG_1453.jpg';
import image14link from '../../assets/imageSliderPhotos/IMG_1672.jpg';
import image15link from '../../assets/imageSliderPhotos/IMG_4969.jpg';
import image16link from '../../assets/imageSliderPhotos/IMG_3709.jpg';
import image17link from '../../assets/imageSliderPhotos/IMG_3421.JPG';
import image18link from '../../assets/imageSliderPhotos/IMG_3365.jpg';
import image19link from '../../assets/imageSliderPhotos/IMG_3165.jpg';
import image20link from '../../assets/imageSliderPhotos/IMG_3024.jpg';
import image21link from '../../assets/imageSliderPhotos/IMG_0727.jpg';
import image22link from '../../assets/imageSliderPhotos/IMG_0825.jpg';
import image23link from '../../assets/imageSliderPhotos/IMG_2305.jpg';
import image24link from '../../assets/imageSliderPhotos/IMG_1002.jpg';
import image25link from '../../assets/imageSliderPhotos/IMG_2739.jpg';
import image26link from '../../assets/imageSliderPhotos/IMG_2955.jpg';
import image27link from '../../assets/imageSliderPhotos/IMG_3230.JPG';
import image28link from '../../assets/imageSliderPhotos/IMG_4841.jpg';
import image29link from '../../assets/imageSliderPhotos/IMG_2393.jpg';
import image30link from '../../assets/imageSliderPhotos/IMG_7501.jpg';

export default function imageSliderLoader() {
    const image1 = document.querySelector('#image1'); 
    const image2 = document.querySelector('#image2'); 
    const image3 = document.querySelector('#image3'); 
    const image4 = document.querySelector('#image4');
    const image5 = document.querySelector('#image5'); 
    const image6 = document.querySelector('#image6'); 
    const image7 = document.querySelector('#image7'); 
    const image8 = document.querySelector('#image8');
    const image9 = document.querySelector('#image9'); 
    const image10 = document.querySelector('#image10'); 
    const image11 = document.querySelector('#image11'); 
    const image12 = document.querySelector('#image12'); 
    const image13 = document.querySelector('#image13'); 
    const image14 = document.querySelector('#image14');
    const image15 = document.querySelector('#image15'); 
    const image16 = document.querySelector('#image16'); 
    const image17 = document.querySelector('#image17'); 
    const image18 = document.querySelector('#image18');
    const image19 = document.querySelector('#image19'); 
    const image20 = document.querySelector('#image20'); 
    const image21 = document.querySelector('#image21'); 
    const image22 = document.querySelector('#image22'); 
    const image23 = document.querySelector('#image23'); 
    const image24 = document.querySelector('#image24');
    const image25 = document.querySelector('#image25'); 
    const image26 = document.querySelector('#image26'); 
    const image27 = document.querySelector('#image27'); 
    const image28 = document.querySelector('#image28');
    const image29 = document.querySelector('#image29'); 
    const image30 = document.querySelector('#image30'); 

    image1.src = image1link; 
    image2.src = image2link; 
    image3.src = image3link; 
    image4.src = image4link;
    image5.src = image5link; 
    image6.src = image6link; 
    image7.src = image7link; 
    image8.src = image8link;
    image9.src = image9link; 
    image10.src = image10link; 
    image11.src = image11link; 
    image12.src = image12link; 
    image13.src = image13link; 
    image14.src = image14link;
    image15.src = image15link; 
    image16.src = image16link; 
    image17.src = image17link; 
    image18.src = image18link;
    image19.src = image19link; 
    image20.src = image20link; 
    image21.src = image21link; 
    image22.src = image22link; 
    image23.src = image23link; 
    image24.src = image24link;
    image25.src = image25link; 
    image26.src = image26link; 
    image27.src = image27link; 
    image28.src = image28link;
    image29.src = image29link; 
    image30.src = image30link; 
}